version: 0.2

phases:
  install:
    commands:
      - echo yum update and upgrade...
      - yum update -y
      - yum upgrade -y
      - yum install -y https://dev.mysql.com/get/mysql84-community-release-el9-1.noarch.rpm
      - yum install -y mysql-community-server

  pre_build:
    commands:
      - echo Starting MySQL service...
      - mysqld --initialize-insecure --datadir=/var/lib/mysql
      - mysqld --daemonize --datadir=/var/lib/mysql
      - sleep 10
      - echo Creating database and user...
      - mysql -u root -e "CREATE DATABASE calender;"
      - mysql -u root -e "CREATE USER 'choi'@'localhost' IDENTIFIED BY 'm98dev09tmd@*';"
      - mysql -u root -e "GRANT ALL PRIVILEGES ON calender.* TO 'choi'@'localhost';"
      - mysql -u root -e "FLUSH PRIVILEGES;"
      - echo Running SQL script...
      - mysql -u choi -pm98dev09tmd@* calender < src/main/resources/scripts/migrations/20240806_cicd_init_table.sql
      - echo Logging in to Amazon ECR...
      - export AWS_DEFAULT_REGION=ap-northeast-2
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 381491842895.dkr.ecr.ap-northeast-2.amazonaws.com
      - REPOSITORY_URI=381491842895.dkr.ecr.ap-northeast-2.amazonaws.com/myapp-ecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building the application with Gradle...
      - ./gradlew clean build --stacktrace --info
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"myapp-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json